site_name: StochTree
site_url: "https://stochtree.ai/"
site_description: "Stochastic tree ensembles (i.e. BART, XBART) for supervised learning and causal inference"
repo_url: "https://github.com/StochasticTree/stochtree"
repo_name: "StochasticTree/stochtree"
theme:
  name: material
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.footer
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
nav:
  - Home: index.md
  - 'Getting Started': getting-started.md
  - 'About StochTree': about.md
  - 'R Package': 
    - 'R Package': R_docs/index.md
    - 'Pkgdown Site': 'R_docs/pkgdown/index.html'
  - 'Python Package':
    - 'Python Package': python_docs/index.md
    - 'API': 
      - 'API': python_docs/api/index.md
      - 'BART': python_docs/api/bart.md
      - 'BCF': python_docs/api/bcf.md
      - 'Low level interface': 
        - 'Low level interface': python_docs/api/low-level/index.md
        - 'Data API': python_docs/api/low-level/dataset.md
        - 'Forest API': python_docs/api/low-level/forest.md
        - 'Sampler API': python_docs/api/low-level/sampler.md
        - 'Utilies API': python_docs/api/low-level/utilities.md
    - 'Demo': 
      - 'Demo': python_docs/demo/index.md
      - 'BART': python_docs/demo/supervised_learning.ipynb
      - 'BCF': python_docs/demo/causal_inference.ipynb
      - 'Heteroskedastic BART': python_docs/demo/heteroskedastic_supervised_learning.ipynb
      - 'Multivariate treatment BCF': python_docs/demo/multivariate_treatment_causal_inference.ipynb
      - 'Model Serialization': python_docs/demo/serialization.ipynb
      - 'Internal Tree Inspection': python_docs/demo/tree_inspection.ipynb
      - 'Low-Level Interface': python_docs/demo/prototype_interface.ipynb
  - 'C++ Core API and Architecture':
    - 'C++ Core API and Architecture': cpp_docs/index.md
    - 'Tracking Data Structures': cpp_docs/tracking.md
    - 'C++ Doxygen Site': 'cpp_docs/doxygen/index.html'
  - 'Development': 
    - 'Development': development/index.md
    - 'Contributing': development/contributing.md
    - 'Roadmap': development/roadmap.md
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/StochasticTree/stochtree
      name: stochtree on Github
  generator: false
copyright: Copyright &copy; 2023 - 2025 Drew Herren, Carlos Carvalho, Richard Hahn, Jared Murray
markdown_extensions:
  - tables
  - toc:
      permalink: "#"
      toc_depth: 3
      baselevel: 1
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - offline
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_signature: true
            line_length: 60
            heading_level: 2
            show_root_heading: true
            docstring_options:
              ignore_init_summary: true
  - mkdocs-jupyter:
      execute: true
      include_source: True
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
