on:
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

name: docs

jobs:
  docs:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: docs-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout documentation repo
        uses: actions/checkout@v4

      - name: Checkout stochtree repo
        uses: actions/checkout@v4
        with:
          repository: 'StochasticTree/stochtree'
          path: 'stochtree_repo'
          submodules: 'recursive'
    
      - name: Install doxygen and graphviz
        run: |
          sudo apt-get install doxygen graphviz -y
    
      - name: Build the C++ doxygen output
        run: |
          sed -i 's|^OUTPUT_DIRECTORY *=.*|OUTPUT_DIRECTORY = ../docs/cpp_docs/|' stochtree_repo/Doxyfile
          sed -i 's|^GENERATE_XML *=.*|GENERATE_XML = NO|' stochtree_repo/Doxyfile
          sed -i 's|^GENERATE_HTML *=.*|GENERATE_HTML = YES|' stochtree_repo/Doxyfile
          mkdir -p docs/cpp_docs/
          cd stochtree_repo
          doxygen Doxyfile
          cd ..
      
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install python dependencies for the doc site and stochtree python package
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install local copy of the stochtree python package
        run: |
          cd stochtree_repo
          pip install .
          cd ..

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: 'stochtree_repo'
          extra-packages: any::latex2exp, any::ggplot2, any::decor, any::pkgdown
          needs: website

      - name: Build R doc site
        run: |
          cd stochtree_repo
          Rscript cran-bootstrap.R 1 1 1
          cd ..
          mkdir -p docs/R_docs/pkgdown
          Rscript -e 'pkgdown::build_site_github_pages("stochtree_repo/stochtree_cran", dest_dir = "../../docs/R_docs/pkgdown", install = TRUE)'

      - name: Clean up the temporary stochtree_cran directory created
        run: |
          cd stochtree_repo
          Rscript cran-cleanup.R 
          cd ..

      - name: Copy Jupyter notebook demos over to docs directory
        run: |
          cp stochtree_repo/demo/notebooks/supervised_learning.ipynb docs/python_docs/demo/supervised_learning.ipynb
          cp stochtree_repo/demo/notebooks/causal_inference.ipynb docs/python_docs/demo/causal_inference.ipynb
          cp stochtree_repo/demo/notebooks/heteroskedastic_supervised_learning.ipynb docs/python_docs/demo/heteroskedastic_supervised_learning.ipynb
          cp stochtree_repo/demo/notebooks/multivariate_treatment_causal_inference.ipynb docs/python_docs/demo/multivariate_treatment_causal_inference.ipynb
          cp stochtree_repo/demo/notebooks/serialization.ipynb docs/python_docs/demo/serialization.ipynb
          cp stochtree_repo/demo/notebooks/tree_inspection.ipynb docs/python_docs/demo/tree_inspection.ipynb
          cp stochtree_repo/demo/notebooks/prototype_interface.ipynb docs/python_docs/demo/prototype_interface.ipynb

      - name: Copy static vignettes over to docs directory
        run: |
          cp vignettes/Python/RDD/rdd.html docs/vignettes/Python/rdd.html
          cp vignettes/Python/RDD/RDD_DAG.png docs/vignettes/Python/RDD_DAG.png
          cp vignettes/Python/RDD/trees1.png docs/vignettes/Python/trees1.png
          cp vignettes/Python/RDD/trees2.png docs/vignettes/Python/trees2.png
          cp vignettes/Python/RDD/trees3.png docs/vignettes/Python/trees3.png
          cp vignettes/R/RDD/rdd.html docs/vignettes/R/rdd.html
          cp vignettes/Python/IV/iv.html docs/vignettes/Python/iv.html
          cp vignettes/Python/IV/IV_CDAG.png docs/vignettes/Python/IV_CDAG.png
          cp vignettes/R/IV/iv.html docs/vignettes/R/iv.html
      
      - name: Build the overall doc site
        run: |
          mkdocs build

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site