name: Generate C++ Documentation

on:
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC

jobs:
  build_cpp_docs:
    name: Build C++ Documentation
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      BRANCH_NAME: docs-temp-${{ github.run_id }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Documentation Repo
        uses: actions/checkout@v4

      - name: Checkout Stochtree Repository
        uses: actions/checkout@v4
        with:
          repository: 'StochasticTree/stochtree'
          path: 'stochtree-repo'
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen nodejs npm -y
          sudo npm install -g moxygen

      - name: Generate Documentation
        run: |
          cd stochtree-repo
          doxygen -g Doxyfile
          sed -i 's|^INPUT *=.*|INPUT = src|' Doxyfile
          sed -i 's|^GENERATE_XML *= NO|GENERATE_XML = YES|' Doxyfile
          sed -i 's|^RECURSIVE *= NO|RECURSIVE = YES|' Doxyfile
          sed -i 's|^OUTPUT_DIRECTORY *=.*|OUTPUT_DIRECTORY = doxygen_output|' Doxyfile
          sed -i 's|^PROJECT_NAME *=.*|PROJECT_NAME = "stochtree"|' Doxyfile
          doxygen Doxyfile

          mkdir -p ../docs/c-documentation-markdown
          moxygen --output ../docs/c-documentation-markdown/index.md doxygen_output/xml

      - name: Commit and Push Documentation Changes
        id: commit_and_push
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git checkout -b $BRANCH_NAME
            git add docs/c-documentation-markdown
            git commit -m "Updated C++ documentation"
            git push origin $BRANCH_NAME
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit."
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge and Clean Up Branch
        if: steps.commit_and_push.outputs.changes == 'true'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git fetch origin main
          git checkout main
          git merge --no-ff $BRANCH_NAME -m "Merge updated C++ documentation"
          git push origin main
          git branch -D $BRANCH_NAME
          git push origin --delete $BRANCH_NAME
