name: Generate Python Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_python_docs:
    name: Build Python Documentation
    runs-on: ubuntu-latest

    permissions:
      contents: write # Grants permission to push to the repository
      pull-requests: write # Grants permission to create and manage pull requests

    env:
      BRANCH_NAME: python-docs-temp-${{ github.run_id }}

    steps:
      - name: Checkout Documentation Repo
        uses: actions/checkout@v4

      - name: Checkout Stochtree Monorepo
        uses: actions/checkout@v4
        with:
          repository: 'StochasticTree/stochtree'
          path: 'stochtree-repo'
          submodules: 'recursive'

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Package with Relevant Dependencies
        working-directory: stochtree-repo
        run: |
          pip install --upgrade pip
          pip install -r python_docs/requirements.txt
          pip install .

      - name: Build HTML Documentation
        working-directory: stochtree-repo
        run: |
          sphinx-build -M html python_docs/source/ python_docs/_build/

      - name: Copy Documentation to Docs Directory
        run: |
          # Ensure the target directory exists
          mkdir -p docs/python-documentation
          # Clear existing content, if present
          rm -rf docs/python-documentation/*
          # Copy the built documentation
          cp -r stochtree-repo/python_docs/_build/html/* docs/python-documentation/

      - name: Commit and Push Documentation Changes
        id: commit_and_push
        run: |
          # Configure Git
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          # Check for changes
          if [ -n "$(git status --porcelain)" ]; then
            # Create and switch to new branch
            git checkout -b $BRANCH_NAME
            # Add changes
            git add docs/python-documentation
            git commit -m "Updated the Python documentation"
            # Push changes to new branch
            git push origin $BRANCH_NAME
            echo "::set-output name=changes::true"
          else
            echo "No changes to commit."
            echo "::set-output name=changes::false"
          fi

      - name: Merge Temporary Branch into Main
        if: steps.commit_and_push.outputs.changes == 'true'
        run: |
          # Configure Git
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          # Fetch the latest main
          git fetch origin main
          # Checkout main
          git checkout main
          # Merge the temporary branch
          git merge --no-ff $BRANCH_NAME -m "Merge updated documentation"
          # Push changes to main
          git push origin main

      - name: Delete Temporary Branch
        if: steps.commit_and_push.outputs.changes == 'true'
        run: |
          # Delete the temporary branch locally and remotely
          git branch -D $BRANCH_NAME
          git push origin --delete $BRANCH_NAME
